### ISSUE TITLE
Panic when running latest Mac.AMD64.gz on macOS 10.13.4 (17E202) 

### ISSUE THREAD

**Issue by ashmckenzie** [git-lfs/lfs-test-server#77]
```
$ ./lfs-test-server
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x1933f5]

goroutine 1 [running]:
github.com/boltdb/bolt.(*Bucket).inlineable(0x0, 0x10)
	/Users/scott/src/gocode/src/github.com/github/lfs-test-server/Godeps/_workspace/src/github.com/boltdb/bolt/bucket.go:553 +0x5
github.com/boltdb/bolt.(*Bucket).spill(0xc8200f6838, 0x0, 0x0)
	/Users/scott/src/gocode/src/github.com/github/lfs-test-server/Godeps/_workspace/src/github.com/boltdb/bolt/bucket.go:499 +0x105
github.com/boltdb/bolt.(*Tx).Commit(0xc8200f6820, 0x0, 0x0)
	/Users/scott/src/gocode/src/github.com/github/lfs-test-server/Godeps/_workspace/src/github.com/boltdb/bolt/tx.go:150 +0x1d4
github.com/boltdb/bolt.(*DB).Update(0xc820071520, 0xc8203e3d58, 0x0, 0x0)
	/Users/scott/src/gocode/src/github.com/github/lfs-test-server/Godeps/_workspace/src/github.com/boltdb/bolt/db.go:512 +0x11d
main.NewMetaStore(0x505cf8, 0x6, 0x779c40, 0x0, 0x0)
	/Users/scott/src/gocode/src/github.com/github/lfs-test-server/meta_store.go:47 +0xc3
main.main()
	/Users/scott/src/gocode/src/github.com/github/lfs-test-server/main.go:85 +0x8fc

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 19 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

**Comment by ttaylorr** [comment]
Hi @ashmckenzie, can you let me know of the specific steps you took to compile and run this?

**Comment by ashmckenzie** [comment]
@ttaylorr the https://github.com/git-lfs/lfs-test-server/releases/tag/v0.3.0 download causes the above, is from 2015 so probably explains it :)

**Comment by ttaylorr** [comment]
@ashmckenzie can you try to download and compile the latest version of `lfs-test-server`? If you're still having issues please do not hesitate to let me know here and I'd be more than happy to re-open this issue. Thanks!

**Comment by ashmckenzie** [comment]
The latest version compiles and executes cleanly, just the most recent downloadable does not work.

**Comment by ttaylorr** [comment]
@ashmckenzie Thanks, I've updated the latest release [here](https://github.com/git-lfs/lfs-test-server/releases/tag/v0.4.0)

**Comment by ashmckenzie** [comment]
Swift work again! The binaries don't appear to be there (yet?), but nice work :)

**Comment by forresthopkinsa** [comment]
First time running it, you get:

```
unexpected fault address 0xb01dfacedebac1e
fatal error: fault
[signal 0xb code=0x1 addr=0xb01dfacedebac1e pc=0x1933bb]

goroutine 1 [running]:
runtime.throw(0x4f6818, 0x5)
	/usr/local/go/src/runtime/panic.go:527 +0x90 fp=0xc8203dd8c8 sp=0xc8203dd8b0
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:27 +0x2ba fp=0xc8203dd918 sp=0xc8203dd8c8
github.com/boltdb/bolt.(*Bucket).spill(0xc8200f0c48, 0x0, 0x0)
	/Users/scott/src/gocode/src/github.com/github/lfs-test-server/Godeps/_workspace/src/github.com/boltdb/bolt/bucket.go:510 +0xc2b fp=0xc8203ddb98 sp=0xc8203dd918
github.com/boltdb/bolt.(*Tx).Commit(0xc8200f0c30, 0x0, 0x0)
	/Users/scott/src/gocode/src/github.com/github/lfs-test-server/Godeps/_workspace/src/github.com/boltdb/bolt/tx.go:150 +0x1d4 fp=0xc8203ddcc0 sp=0xc8203ddb98
github.com/boltdb/bolt.(*DB).Update(0xc82006f520, 0xc8203ddd58, 0x0, 0x0)
	/Users/scott/src/gocode/src/github.com/github/lfs-test-server/Godeps/_workspace/src/github.com/boltdb/bolt/db.go:512 +0x11d fp=0xc8203ddd18 sp=0xc8203ddcc0
main.NewMetaStore(0x505cf8, 0x6, 0x779c40, 0x0, 0x0)
	/Users/scott/src/gocode/src/github.com/github/lfs-test-server/meta_store.go:47 +0xc3 fp=0xc8203ddd88 sp=0xc8203ddd18
main.main()
	/Users/scott/src/gocode/src/github.com/github/lfs-test-server/main.go:85 +0x8fc fp=0xc8203ddf20 sp=0xc8203ddd88
runtime.main()
	/usr/local/go/src/runtime/proc.go:111 +0x2b0 fp=0xc8203ddf70 sp=0xc8203ddf20
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8203ddf78 sp=0xc8203ddf70

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 19 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

And then the second time, you get the stack trace posted above.

Looks like there still aren't any binaries for version 0.4.0.

**Comment by bk2204** [comment]
We're not doing regular releases of the lfs-test-server, so if you're looking for binaries, you'll need to build them yourself from the main branch.

**Comment by forresthopkinsa** [comment]
Tried building the 0.4.0 release using the Dockerfile and got Go errors:

```
+ exec go get -v -d
github.com/GeertJohan/go.rice (download)
github.com/daaku/go.zipexe (download)
github.com/boltdb/bolt (download)
github.com/gorilla/context (download)
github.com/gorilla/mux (download)
import "context": import path does not contain a slash
package github.com/GeertJohan/go.rice
	imports github.com/GeertJohan/go.rice/embedded
	imports github.com/daaku/go.zipexe
	imports github.com/boltdb/bolt
	imports github.com/gorilla/context
	imports github.com/gorilla/mux
	imports context: unrecognized import path "context"
```

I know this is a different issue, but probably worth mentioning. Ended up figuring out a different LFS solution anyway so it's not a problem for me, just thought you may want to know.

**Comment by bk2204** [comment]
I'll fix the Dockerfile.  You can simply run `go build` and it should build correctly.
